name: PepperShop
main: cn.innc11.peppershop.PepperShop
version: "1.4.1"
author: innc11
api: ["1.0.0"]
load: POSTWORLD
depend: ["EconomyAPI"]
softdepend: ["Residence", "Land"]
website: "https://github.com/innc11/PepperShop"
description: "&l&ePepperShop&r, &dRemade by innc11, original author WetABQ"